In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt

In [4]:
df = pd.read_csv('../Resources/NationalForestSystemTrails.csv')
df.head()

,TRAIL_NO,TRAIL_NAME,TRAIL_TYPE,TRAIL_CN,BMP,EMP,SEGMENT_LENGTH,ADMIN_ORG,MANAGING_ORG,SECURITY_ID,...,MOTOR_WATERCRAFT_RESTRICTED,NONMOTOR_WATERCRAFT_MANAGED,NONMOTOR_WATERCRAFT_ACCPT_DISC,NONMOTOR_WATERCRAFT_RESTRICTED,GIS_MILES,TERRA_MOTORIZED,SNOW_MOTORIZED,WATER_MOTORIZED,OBJECTID,SHAPE_Length
0,291,DREW CANYON,TERRA,1.163101e+10,0.0,0.535,0.535,30102,30102,301,...,NaN,NaN,NaN,NaN,0.542,NaN,NaN,NaN,1,1054.873841
1,602C,OSPREY,TERRA,1.160901e+10,0.0,0.375,0.375,30106,30106,301,...,NaN,NaN,NaN,NaN,0.381,NaN,NaN,NaN,2,728.075541
2,648,MEADOWVIEW,TERRA,1.261001e+10,0.0,0.212,0.212,30107,30107,301,...,NaN,NaN,NaN,NaN,0.207,NaN,NaN,NaN,3,412.691543
3,107C,PINEVIEW CONNECTOR,TERRA,1.260101e+10,0.0,0.230,0.230,30107,30107,301,...,NaN,NaN,NaN,NaN,0.238,NaN,NaN,NaN,4,445.207838
4,602G,GROUSE,TERRA,1.160501e+10,0.0,1.200,1.200,30106,30106,301,...,NaN,NaN,NaN,NaN,1.169,NaN,NaN,NaN,5,2244.851243

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 64 columns):
TRAIL_NO                          1000 non-null object
TRAIL_NAME                        764 non-null object
TRAIL_TYPE                        1000 non-null object
TRAIL_CN                          1000 non-null float64
BMP                               1000 non-null float64
EMP                               1000 non-null float64
SEGMENT_LENGTH                    1000 non-null float64
ADMIN_ORG                         1000 non-null int64
MANAGING_ORG                      1000 non-null int64
SECURITY_ID                       1000 non-null int64
ATTRIBUTESUBSET                   1000 non-null object
NATIONAL_TRAIL_DESIGNATION        1000 non-null int64
TRAIL_CLASS                       1000 non-null object
TERRA_BASE_SYMBOLOGY              963 non-null object
ACCESSIBILITY_STATUS              142 non-null object
TRAIL_SURFACE                     374 non-null object
SURFACE_FIRMNESS                  9 non-null object
TYPICAL_TRAIL_GRADE               363 non-null object
TYPICAL_TREAD_WIDTH               223 non-null object
MINIMUM_TRAIL_WIDTH               15 non-null object
TYPICAL_TREAD_CROSS_SLOPE         11 non-null object
SPECIAL_MGMT_AREA                 13 non-null object
MVUM_SYMBOL                       1000 non-null int64
ALLOWED_TERRA_USE                 0 non-null float64
ALLOWED_SNOW_USE                  0 non-null float64
HIKER_PEDESTRIAN_MANAGED          0 non-null float64
HIKER_PEDESTRIAN_ACCPT_DISC       0 non-null float64
HIKER_PEDESTRIAN_RESTRICTED       0 non-null float64
PACK_SADDLE_MANAGED               0 non-null float64
PACK_SADDLE_ACCPT_DISC            0 non-null float64
PACK_SADDLE_RESTRICTED            0 non-null float64
BICYCLE_MANAGED                   0 non-null float64
BICYCLE_ACCPT_DISC                0 non-null float64
BICYCLE_RESTRICTED                0 non-null float64
MOTORCYCLE_MANAGED                0 non-null float64
MOTORCYCLE_ACCPT_DISC             0 non-null float64
MOTORCYCLE_RESTRICTED             0 non-null float64
ATV_MANAGED                       0 non-null float64
ATV_ACCPT_DISC                    0 non-null float64
ATV_RESTRICTED                    0 non-null float64
FOURWD_MANAGED                    0 non-null float64
FOURWD_ACCPT_DISC                 0 non-null float64
FOURWD_RESTRICTED                 0 non-null float64
SNOWMOBILE_MANAGED                0 non-null float64
SNOWMOBILE_ACCPT_DISC             0 non-null float64
SNOWMOBILE_RESTRICTED             0 non-null float64
SNOWSHOE_MANAGED                  0 non-null float64
SNOWSHOE_ACCPT_DISC               0 non-null float64
SNOWSHOE_RESTRICTED               0 non-null float64
XCOUNTRY_SKI_MANAGED              0 non-null float64
XCOUNTRY_SKI_ACCPT_DISC           0 non-null float64
XCOUNTRY_SKI_RESTRICTED           0 non-null float64
MOTOR_WATERCRAFT_MANAGED          0 non-null float64
MOTOR_WATERCRAFT_ACCPT_DISC       0 non-null float64
MOTOR_WATERCRAFT_RESTRICTED       0 non-null float64
NONMOTOR_WATERCRAFT_MANAGED       0 non-null float64
NONMOTOR_WATERCRAFT_ACCPT_DISC    0 non-null float64
NONMOTOR_WATERCRAFT_RESTRICTED    0 non-null float64
GIS_MILES                         1000 non-null float64
TERRA_MOTORIZED                   0 non-null float64
SNOW_MOTORIZED                    0 non-null float64
WATER_MOTORIZED                   0 non-null float64
OBJECTID                          1000 non-null int64
SHAPE_Length                      846 non-null float64
dtypes: float64(44), int64(6), object(14)
memory usage: 500.1+ KB

##Look up metadata for##  
TRAIL_CN, BMP, EMP

In [15]:
df_skinny = df[['TRAIL_NO', 'TRAIL_NAME', 'TRAIL_TYPE', 'SEGMENT_LENGTH', 'ADMIN_ORG', 'MANAGING_ORG']]
df_skinny.head()

,TRAIL_NO,TRAIL_NAME,TRAIL_TYPE,SEGMENT_LENGTH,ADMIN_ORG,MANAGING_ORG
0,291,DREW CANYON,TERRA,0.535,30102,30102
1,602C,OSPREY,TERRA,0.375,30106,30106
2,648,MEADOWVIEW,TERRA,0.212,30107,30107
3,107C,PINEVIEW CONNECTOR,TERRA,0.230,30107,30107
4,602G,GROUSE,TERRA,1.200,30106,30106